### ISSUE TITLE
I have a problem store scarlet

### ISSUE THREAD

**Issue by Doctor2023** [DebianArch64/Scarlet#11]
![IMG_0568](https://user-images.githubusercontent.com/129991276/230983914-076bd551-4258-40ae-929a-35213ffb1231.jpeg)
![IMG_0567](https://user-images.githubusercontent.com/129991276/230983921-498e01b9-84b5-4e8c-8794-29f3c88f0986.jpeg)

I get these problems in the scarlet  store

**Comment by DebianArch64** [comment]
> ![IMG_0568](https://user-images.githubusercontent.com/129991276/230983914-076bd551-4258-40ae-929a-35213ffb1231.jpeg) ![IMG_0567](https://user-images.githubusercontent.com/129991276/230983921-498e01b9-84b5-4e8c-8794-29f3c88f0986.jpeg)
> 
> I get these problems in the scarlet store

If you're on Mac make sure the Mail app is opened.
If on Windows read the black window it'll tell you what to do
