### ISSUE TITLE
I can’t sign to iCloud 

### ISSUE THREAD

**Issue by JackkMax** [DebianArch64/Scarlet#16]
I use Windows and I can’t sign in to my iCloud so i can use scarlet because i use old version 7.21.0.23 and I can’t download from apple site
Is there a link to download newer iCloud you can give me please?

**Comment by DebianArch64** [comment]
> I use Windows and I can’t sign in to my iCloud so i can use scarlet because i use old version 7.21.0.23 and I can’t download from apple site Is there a link to download newer iCloud you can give me please?

Here is the YouTube tutorial for Scarlet on windows. You need to download the exe it can't be from the microsoft store

https://youtu.be/xwbX_1JR4Zo

**Comment by JackkMax** [comment]
Thank you so much ❤️

**Comment by DebianArch64** [comment]
> Thank you so much ❤️

No problem ;)
Also I'm a bit inactive here, but if you want to contact me on discord it's DebianArch#1935
