### ISSUE TITLE
Cant install or run scarlet

### ISSUE THREAD

**Issue by NinV1-GOD** [DebianArch64/Scarlet#18]
i was opening up nulls clash and it came up with an error message long story short all apps related to scarlet wont open i went to re install it and it says revoked on the site. i know this is probably dumb
iphone 11
ios 16.0.1

**Comment by DebianArch64** [comment]
> says

That's what revoke means - apple pretty much untrusted the certificate and when it says signed it means good to install again

To keep app progress next time follow this:
https://docs.usescarlet.com/scarlet/backup-restore-normal
