### ISSUE TITLE
App crashes almost immediately when opened.

### ISSUE THREAD

**Issue by VirtualComputersVM** [DebianArch64/Scarlet#21]
I installed Crimson on an iPhone 7 running iOS 15.7.3, I opened the app and it almost immedately crashes. Screen recording below. Anyway to fix this issue? (Preferably without updating iOS)

https://github.com/DebianArch64/Scarlet/assets/134581779/f74b675e-7d37-4cb1-8cb0-aad89e1f4c1b

**Comment by DebianArch64** [comment]
Crimson doesn't exist 

https://usescarlet.com
