### ISSUE TITLE
Scartlet cloud didn't sign apps from another repos

### ISSUE THREAD

**Issue by macrochel** [DebianArch64/Scarlet#25]
Scartlet cloud didn't sign apps from another repos.

When I install apps from scarlet's repo - everything work good. But when I try to install app from other repos, I get "Unable To Install ..."

**Comment by DebianArch64** [comment]
> Scartlet cloud didn't sign apps from another repos.
> 
> When I install apps from scarlet's repo - everything work good. But when I try to install app from other repos, I get "Unable To Install ..."

This doesn't have to do with Scarlet. Scarlet installs every app the same way doesn't matter whether it came from my repo or not.

If using the computer method you are limited to three apps at a time it's a restriction by apple and scarlet app is included towards that limit
