### ISSUE TITLE
Redirect problem

### ISSUE THREAD

**Issue by metamxrphine** [DebianArch64/Scarlet#29]
Downloaded Scarlet for win, all working good, Scarlet is installed on phone, but when i'm trying to install something with Scarlet it's stuck on 60-70% and then just nothing happens, it's also appears with this![image](https://github.com/DebianArch64/Scarlet/assets/116524068/a551ce9a-361a-4a5b-a755-583c6dd2eed9)

**Comment by Tigerfy** [comment]
I have the same exact issue. Anyone knows solution?

**Comment by bilal20115** [comment]
how do I fix it does anyone know?

**Comment by DebianArch64** [comment]
Connect to wireguard instead of computer
