### ISSUE TITLE
Everytime it stucks at 75%

### ISSUE THREAD

**Issue by saur8bh** [DebianArch64/Scarlet#30]
**Terminal Screenshot:** 
![Screenshot_21](https://github.com/DebianArch64/Scarlet/assets/81372210/ebd2426f-b8af-441f-91b4-c4e1a172c550)

**iPad Screenshot:**
![photo_2023-10-14_10-47-40](https://github.com/DebianArch64/Scarlet/assets/81372210/5b94c176-bfb4-4d93-81de-808c4543d29e)

**Comment by bilal20115** [comment]
how do I fix it does anyone know?

**Comment by DebianArch64** [comment]
Use wireguard instead of being connected to comp
