### ISSUE TITLE
how do i fix this error "Invalid info.plist

### ISSUE THREAD

**Issue by JabezLlave** [DebianArch64/Scarlet#32]
![IMG_0278](https://github.com/DebianArch64/Scarlet/assets/100693409/23f8cd7a-8540-4abb-b190-a6e12decd2ba)

pls help im literally crying😭😭😭

**Comment by DebianArch64** [comment]
> ![IMG_0278](https://user-images.githubusercontent.com/100693409/280412340-23f8cd7a-8540-4abb-b190-a6e12decd2ba.png)
> 
> pls help im literally crying😭😭😭

Means invalid IPA

**Comment by JabezLlave** [comment]
what do i do 😭😭😭

**Comment by justblitz** [comment]
> what do i do 😭😭😭

as he said is not your problem is the .ipa file invalid, so search a new ipa and try with it

**Comment by JabezLlave** [comment]
what do you mean by search a new ipa? -asking politely

**Comment by justblitz** [comment]
> what do you mean by search a new ipa? -asking politely

you are trying to install an invalid ipa file, search a working/valid ipa and try with it

**Comment by JabezLlave** [comment]
i did try all the existing files, nothing works. Also if i download the roblox scriptware its stuck on 49%
![Uploading IMG_0281.png…]()

**Comment by justblitz** [comment]
> i did try all the existing files, nothing works. Also if i download the roblox scriptware its stuck on 49%
> 
> ![Uploading IMG_0281.png…]()
> 
> 

thats weird...i hope and i think you try to uninstall and reinstall scarlet, if you didn't try to uninstall and install. If the problem continue to happen wait a response from the developer (timezone: GMT-5 Texas). That kind of bug is never happen to me and i have external repos installed

**Comment by JabezLlave** [comment]
yeah, i reinstall it . Also thankyouuu!

**Comment by justblitz** [comment]
> yeah, i reinstall it . it still showing error, thanks doe!

so wait for a response from DebArch. You are welcome

**Comment by andreped** [comment]
> Means invalid IPA

@DebianArch64 Does the IPA need to be signed before it can be installed on the iOS device?
I am fairly certain that there is nothing wrong with the IPA except that it is not signed.
I don't own an Apple Developer Certificate, hence why I am asking.

**Comment by DebianArch64** [comment]
> > Means invalid IPA
> 
> @DebianArch64 Does the IPA need to be signed before it can be installed on the iOS device? I am fairly certain that there is nothing wrong with the IPA except that it is not signed. I don't own an Apple Developer Certificate, hence why I am asking.

The whole point of Scarlet is that it signs the app, if your using the computer method it'll use ANY account to sign the apps automatically. If using 'Direct Install' it'll use an enterprise certificate or you can import your own

I've been getting tons of death threats so I am going to be inactive until the next major release, the computer method is getting a major overhaul won't say much because it's really something special.

**Comment by andreped** [comment]
> I've been getting tons of death threats from competition

Sorry to hear about that. Stay safe!
