### ISSUE TITLE
how to get free certificate without paying 99$

### ISSUE THREAD

**Issue by AdhmAlateiat** [DebianArch64/Scarlet#36]

**Comment by justblitz** [comment]
> 

If you dont want Scarlet revoked on your device just use Anti-Revoke [follow this](https://docs.usescarlet.com/scarlet/anti-revoke).

**Comment by DebianArch64** [comment]
Scarlet computer method was made for this exact reason, it generates a certificate withy your normal account. A computer will always be required initially for this because the systems installd daemon blocks installs with these certificates unless over usbmuxd
