### ISSUE TITLE
iCloud instal problem

### ISSUE THREAD

**Issue by davitoso** [DebianArch64/Scarlet#37]
![Screenshot 2023-11-28 140045](https://github.com/DebianArch64/Scarlet/assets/129310417/53064a29-6d1f-487c-ad96-8e37ed08b36d)

After going through all the installation steps, I get this problem: "There is a problem with this Windows Installer package. A program that ran during the installation terminated unexpectedly. Please contact support personnel or the software vendor. package." This is the .exe file of your link.

**Comment by justblitz** [comment]
> ![Screenshot 2023-11-28 140045](https://github.com/DebianArch64/Scarlet/assets/129310417/53064a29-6d1f-487c-ad96-8e37ed08b36d)
> 
> 
> 
> After going through all the installation steps, I get this problem: "There is a problem with this Windows Installer package. A program that ran during the installation terminated unexpectedly. Please contact support personnel or the software vendor. package." This is the .exe file of your link.
> 
> 
> 
> 

Hai gia provato ad avviarlo come amministratore?

**Comment by davitoso** [comment]
lo avevo ma era quello di microsoft store, poi ho eliminato tutto e ho riscaricato i file setup da qui

**Comment by justblitz** [comment]
> lo avevo ma era quello di microsoft store, poi ho eliminato tutto e ho riscaricato i file setup da qui
> 
> 

hai tolto i file dalla cartella oppure dall ms store

**Comment by davitoso** [comment]
ho disinstallato da pannello di controllo e ho eliminato altri file apple dalle cartelle

**Comment by davitoso** [comment]
ora ho provato a installare anche itunes da ms ma non trovo nessun pulsante disinstalla

**Comment by justblitz** [comment]
> ora ho provato a installare anche itunes da ms ma non trovo nessun pulsante disinstalla
> 
> 

se non ce nel pannello di controllo, dovresti trovarlo nella cartella di iTunes senno dall ms store

**Comment by davitoso** [comment]
no, intendo che non riesco a disinstallarlo dal ms store

**Comment by davitoso** [comment]
son riuscito ora ti faccio vedere che succede se lo installo tramite il link del git di scarlet

**Comment by justblitz** [comment]
> ![Screenshot 2023-11-29 125304](https://github.com/DebianArch64/Scarlet/assets/129310417/1665ed90-1655-4e88-b256-984185ddbd09)
> 
> 

hai gia cercato il file in questione?

**Comment by davitoso** [comment]
![Screenshot 2023-11-29 125428](https://github.com/DebianArch64/Scarlet/assets/129310417/17601e77-83d2-4d11-a074-5d192fb8e16a)

**Comment by davitoso** [comment]
non saprei che fare

**Comment by davitoso** [comment]
non capisco se ce qualche problema a livello del mio computer oppure boh

**Comment by justblitz** [comment]
> non saprei che fare
> 
> 

prova a cancellare il file e rifare l'installazione

**Comment by davitoso** [comment]
ok, itunes risolto grazie
ora per icloud non so

**Comment by justblitz** [comment]
> ok, itunes risolto grazie ora per icloud non so

probabilmente dentro i file ce ancora qualche file rimasto idk

**Comment by justblitz** [comment]
> non so continua a darmi lo stesso errore che "termina in modo imprevisto"

Prova a consultare [questo post](https://support.apple.com/en-us/HT204363)

**Comment by davitoso** [comment]
non saprei provo a aggiornare windows che ho un aggiornamento non fatto

**Comment by davitoso** [comment]
conosci qualche programma gratuito in grado di disinstallare per bene un programma?

**Comment by justblitz** [comment]
> conosci qualche programma gratuito in grado di disinstallare per bene un programma?

Io usavo [iobit](https://www.iobit.com/it/advanceduninstaller.php) e [revo](https://www.revouninstaller.com/it/products/revo-uninstaller-free/)

**Comment by davitoso** [comment]
grazie

**Comment by davitoso** [comment]
sto provando a installare su linux, io ho la versione ubuntu, ma non so che file devo installare tra queste .
![Schermata del 2023-11-30 00-32-54](https://github.com/DebianArch64/Scarlet/assets/129310417/fa51e28a-9fd4-4f38-a08f-57e46630c874)

**Comment by justblitz** [comment]
> sto provando a installare su linux, io ho la versione ubuntu, ma non so che file devo installare tra queste .
> 
> ![Schermata del 2023-11-30 00-32-54](https://github.com/DebianArch64/Scarlet/assets/129310417/fa51e28a-9fd4-4f38-a08f-57e46630c874)
> 
> 

appena posso ti dico quale è il .deb

**Comment by davitoso** [comment]
ho risolto

**Comment by davitoso** [comment]
anche se non so come installarlo

**Comment by justblitz** [comment]
> visto che non riesco a installare icloud su windows, volevo provare a scaricare scarlet su linux (ubuntu), ho gia lanciato il comando (sudo apt-get install usbmuxd) ho scaricato il file scarlet amd64, e non so che fare ora. mi ritrovo con questo file ora ![Schermata del 2023-11-30 13-16-13](https://private-user-images.githubusercontent.com/129310417/286926242-cb448f4b-2e63-4b1f-aa35-30e68674f262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTkwOTEsIm5iZiI6MTcwMTM1ODc5MSwicGF0aCI6Ii8xMjkzMTA0MTcvMjg2OTI2MjQyLWNiNDQ4ZjRiLTJlNjMtNGIxZi1hYTM1LTMwZTY4Njc0ZjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEzMFQxNTM5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjE5MzMwY2NhNDEzZDUxNGVmYjAwMTQ2MjRmMjllMWE1YjMxZWE4NTYyMTkzNzVhZTI3NDVlMzE2YjA4YzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.47GzgBQ0JZk_pYybREAhERzdjKTIPOlg8GVzicXqLCM)

Scusa per l'orario, il file sembra essere un [ELF](https://it.wikipedia.org/wiki/Executable_and_linkable_format) quindi cerca su google come installare i file [ELF](https://it.wikipedia.org/wiki/Executable_and_linkable_format), senno puoi utilizzare [Wine](https://www.winehq.org/).

> [!WARNING]
> Non so se con [Wine](https://www.winehq.org/) funzioni ma credo di si

> [!NOTE]
> [Wine](https://www.winehq.org/) ti permette di usare i file .exe su Linux quindi dovrai usare il [file .exe](https://github.com/DebianArch64/DebProvision/releases/download/GUI/scarletcloudux-windows-386.exe)
