### ISSUE TITLE
Install and use scarlet on linux

### ISSUE THREAD

**Issue by davitoso** [DebianArch64/Scarlet#38]
visto che non riesco a installare icloud su windows, volevo provare a scaricare scarlet su linux (ubuntu), ho gia lanciato il comando (sudo apt-get install usbmuxd) ho scaricato il file scarlet amd64, e non so che fare ora.
 mi ritrovo con questo file ora 
![Schermata del 2023-11-30 13-16-13](https://github.com/DebianArch64/Scarlet/assets/129310417/cb448f4b-2e63-4b1f-aa35-30e68674f262)

**Comment by DebianArch64** [comment]
> visto che non riesco a installare icloud su windows, volevo provare a scaricare scarlet su linux (ubuntu), ho gia lanciato il comando (sudo apt-get install usbmuxd) ho scaricato il file scarlet amd64, e non so che fare ora. mi ritrovo con questo file ora ![Schermata del 2023-11-30 13-16-13](https://private-user-images.githubusercontent.com/129310417/286926242-cb448f4b-2e63-4b1f-aa35-30e68674f262.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MDAwMzEsIm5iZiI6MTcwOTU5OTczMSwicGF0aCI6Ii8xMjkzMTA0MTcvMjg2OTI2MjQyLWNiNDQ4ZjRiLTJlNjMtNGIxZi1hYTM1LTMwZTY4Njc0ZjI2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQwMDQ4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGI0YzBjMzA1M2JmZTgzNmZkNWRmZmM2NGNkYTczNTM1NTVkYmNjYzc0MjEyMTVjMGFiZmI2YWQ0MzI5MzIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-a2io780-a1o6ljIphccVILdIV6ZcQT8h18_PO-r7m0)

You need to mark the executable as executable by using chmod, then you can run it from terminal. Look at tutorial on how to use Linux
