### ISSUE TITLE
Blacklisted

### ISSUE THREAD

**Issue by LifeDreamer24** [DebianArch64/Scarlet#41]
Will i ever get un-blacklisted? I get the connection required message upon opening scarlet. I bought a developper upgrade to use it without limitations but i realized it doesn't go away as soon as i bought it. Is this permanent? Because otherwise im stuck sideloading with my own server opened...

**Comment by DebianArch64** [comment]
The scarlet app you have is signed with an enterprise certificate not your certificate. Anything signed with an enterprise certificate won't work after X days

To use your own paid developer account or certificate visit this page. If you need any more help contact me on discord 'DebianArch':
https://docs.usescarlet.com/scarlet/certificates-developer-login

**Comment by LifeDreamer24** [comment]
You're unreachable on discord as your incoming messages are disabled @DebianArch64
While you accept me, Im going to write here.

Your post on twitter helped me for this BUT by using a vpn constantly. 😕
https://twitter.com/GetScarlet/status/1712113029083451577

For the wiki page you sent me, i already followed it but when clicking on "export account", it simply asked me to install a certificate and switches me to the app without being able to install anything afterwards. It brings me the same page to export my certificate upon installing something.

The best method as of now for me is by using wireguard although it constantly depends on me using a vpn.

Thanks for replying really quickly and happy new year from Canada 😄🎉

**Comment by DebianArch64** [comment]
> You're unreachable on discord as your incoming messages are disabled @DebianArch64 While you accept me, Im going to write here.
> 
> Your post on twitter helped me for this BUT by using a vpn constantly. 😕 https://twitter.com/GetScarlet/status/1712113029083451577
> 
> For the wiki page you sent me, i already followed it but when clicking on "export account", it simply asked me to install a certificate and switches me to the app without being able to install anything afterwards. It brings me the same page to export my certificate upon installing something.
> 
> The best method as of now for me is by using wireguard although it constantly depends on me using a vpn.
> 
> Thanks for replying really quickly and happy new year from Canada 😄🎉

Yeah click export account, after that you'll be promoted to choose a place to save the certificate to

**Comment by LifeDreamer24** [comment]
Downloading the cert only brings me there without downloading anything.
![image](https://github.com/DebianArch64/Scarlet/assets/62817314/1bc5e0b2-8f2d-4354-84c1-ff7b9280dcb4)
Installing it brings me to the app once again.

**Comment by DebianArch64** [comment]
> Downloading the cert only brings me there without downloading anything. ![image](https://private-user-images.githubusercontent.com/62817314/293572774-1bc5e0b2-8f2d-4354-84c1-ff7b9280dcb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTM0NTYsIm5iZiI6MTcwNDA5MzE1NiwicGF0aCI6Ii82MjgxNzMxNC8yOTM1NzI3NzQtMWJjNWUwYjItOGYyZC00MzU0LTg0YzEtZmY3YjkyODBkY2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA3MTIzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjM1N2ZmMTczMWQwNjczZGM5OTMzMjRiODliZjU3MjA5YjNmMTA4N2UyNDM1NDQ3MTY0MDhjZTNhMTQ1YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZZs58w6xQ8lnyLU1qU1d8Qrd3npASxP6C3ihPPLHbDU) Installing it brings me to the app once again.

Yeah that's normal, after that profile is added it'll bring you into scarlet. You'll have to click export account after scarlet opens and it should work

**Comment by LifeDreamer24** [comment]
It doesn't install completely, I think that's the problem
Cause it still shows as a downloaded profile that i can install

**Comment by DebianArch64** [comment]
> It doesn't install completely, I think that's the problem Cause it still shows as a downloaded profile that i can install

Yep that's expected, this is only meant to get your device udid then redirect to Scarlet app no profile is supposed to show permanently

**Comment by DebianArch64** [comment]
> It doesn't install completely, I think that's the problem Cause it still shows as a downloaded profile that i can install

Yeah don't worry about that stuff, as long as the profile opens scarlet it did it's job
