### ISSUE TITLE
Scarlet pc not working 

### ISSUE THREAD

**Issue by luvhabbi** [DebianArch64/Scarlet#42]
I download scarlet using a freinds Mac OS and it worked fine until it started showing this every time I tried downloading anything https://im.ge/i/YWuzty anyone know how to fix this?

**Comment by DebianArch64** [comment]
> I download scarlet using a freinds Mac OS and it worked fine until it started showing this every time I tried downloading anything https://im.ge/i/YWuzty anyone know how to fix this?

Computer methods need access to usbmuxd to sideload. Use wireguard to not require a computer

https://apps.apple.com/app/wireguard/id1441195209

Import this file: https://github.com/DebianArch64/DebProvision/releases/download/GUI/emp.conf

**Comment by luvhabbi** [comment]
Hey sorry to bother you but I downloaded wireguard and put in the file and it says connect but the issue now is that it stays at 0 and says this error
![Uploading IMG_0525.png…]()

**Comment by luvhabbi** [comment]
Hey sorry to bother you but I downloaded wireguard and put in the file and it says connect but the issue now is that it stays at 0 and says this error

**Comment by luvhabbi** [comment]
Sorry I fixed it but do I need to do anything like to restart scarlet every week or something like that or does it stay forever?

**Comment by DebianArch64** [comment]
> Sorry I fixed it but do I need to do anything like to restart scarlet every week or something like that or does it stay forever?

You can renew your apps from your device. On the installed section if you click an app icon it'll show you the expiration left, when it goes low enough hit refresh and it'll bring it up to 7 days
