### ISSUE TITLE
Scarlet app verified but scarlet is not??

### ISSUE THREAD

**Issue by luvhabbi** [DebianArch64/Scarlet#43]
I didn’t open scarlet for 5+ hours and when I came back it kept on crashing? And when I checked on the enterprise it said this??   

![IMG_0568](https://github.com/DebianArch64/Scarlet/assets/153338993/59ab9f2a-6ffc-401d-8e0a-2396176bdf11)

**Comment by DebianArch64** [comment]
> I didn’t open scarlet for 5+ hours and when I came back it kept on crashing? And when I checked on the enterprise it said this??
> 
> ![IMG_0568](https://private-user-images.githubusercontent.com/153338993/299498462-59ab9f2a-6ffc-401d-8e0a-2396176bdf11.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDIzNjMsIm5iZiI6MTcwNjE0MjA2MywicGF0aCI6Ii8xNTMzMzg5OTMvMjk5NDk4NDYyLTU5YWI5ZjJhLTZmZmMtNDAxZC04ZTBhLTIzOTYxNzZiZGYxMS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDAyMTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2M1YjQxYTUxZGI0YWVjOWRkY2MxYzVhYWJlYThlYzM4OGIxY2VjNWEzN2Q3MjgxZGJlYzY2ZTVmNmZjODEwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8w8k_Cc6d8-E8va-2GLik5_2UKH0XPp6_545S5z3bVI)

This is not related to Scarlet, anything that happens in the Scarlet app is related to scarlet.

If the certificate your using revokes it'll cause a crash
