### ISSUE TITLE
Jit

### ISSUE THREAD

**Issue by Montivillon** [DebianArch64/Scarlet#49]
This is not an issue and only a recommendation. If possible, could you make an enable JIT feature because emulators and stuff like pojavlauncher is usually sideloaded with troll store but troll store is not compatible for the latest iOS versions and you can install Scarlet using the direct install. My point is that some people don’t have computers and when we go outside, we can’t enable jit. So I’m suggesting an enable jit feature so that it’s possible to enable jit anywhere with Wi-Fi without the need of computer.

**Comment by DebianArch64** [comment]
> This is not an issue and only a recommendation. If possible, could you make an enable JIT feature because emulators and stuff like pojavlauncher is usually sideloaded with troll store but troll store is not compatible for the latest iOS versions and you can install Scarlet using the direct install. My point is that some people don’t have computers and when we go outside, we can’t enable jit. So I’m suggesting an enable jit feature so that it’s possible to enable jit anywhere with Wi-Fi without the need of computer.

Not possible, JIT is an entitlement how it works with computers is a developer disk image is mounted over usbmuxd and then the usbmuxd service to launch an app with JIT is exposed from that

**Comment by Montivillon** [comment]
I guess
