### ISSUE TITLE
As you said to update the scarlet app, I did and it fix the duplication bug and scarlet refresh bug. But now there is one another bug occurred. We are unable to Refresh any other app rather than scarlet. It gives an error “failed to load info.plist” while refreshing and if we try to refresh again just after that error then it gives another error “failed to create installation proxy”. All we can do is to uninstall the sideloaded app and install it again which also removes the data of app. Methods like turning on/off wireguard emp then reopening scarlet app or turning on/off wifi fixes the issues for the errors while sideloading the app or refreshing the scarlet app itself. But error still persist if we refresh other sideloaded apps even after trying all the above mentioned methods. Do you have any fix for that?

### ISSUE THREAD

**Issue by zin55** [DebianArch64/Scarlet#5]
As you said to update the scarlet app, I did and it fix the duplication bug and scarlet refresh bug. But now there is one another bug occurred. We are unable to Refresh any other app rather than scarlet. It gives an error “failed to load info.plist” while refreshing and if we try to refresh again just after that error then it gives another error “failed to create installation proxy”. All we can do is to uninstall the sideloaded app and install it again which also removes the data of app. Methods like turning on/off wireguard emp then reopening scarlet app or turning on/off wifi fixes the issues for the errors while sideloading the app or refreshing the scarlet app itself. But error still persist if we refresh other sideloaded apps even after trying all the above mentioned methods. Do you have any fix for that?

_Originally posted by @gharshit606 in https://github.com/DebianArch64/DebProvision/issues/65_

**Comment by DebianArch64** [comment]
> As you said to update the scarlet app, I did and it fix the duplication bug and scarlet refresh bug. But now there is one another bug occurred. We are unable to Refresh any other app rather than scarlet. It gives an error “failed to load info.plist” while refreshing and if we try to refresh again just after that error then it gives another error “failed to create installation proxy”. All we can do is to uninstall the sideloaded app and install it again which also removes the data of app. Methods like turning on/off wireguard emp then reopening scarlet app or turning on/off wifi fixes the issues for the errors while sideloading the app or refreshing the scarlet app itself. But error still persist if we refresh other sideloaded apps even after trying all the above mentioned methods. Do you have any fix for that?
> 
> _Originally posted by @gharshit606 in [DebianArch64/DebProvision#65](https://github.com/DebianArch64/DebProvision/issues/65)_

Please stop spam pushing issues or I'll have to block your account. The issue was closed because the person got the issue fixed
