### ISSUE TITLE
Can this work?

### ISSUE THREAD

**Issue by GreatNateDev** [DebianArch64/Scarlet#50]
Make scarlet work with a jailbreak so that I can not use a cert basically make a dev version that will work with Sileo so i can sideload apps I would use TrollStore but i need it too always be set to User not System

**Comment by DebianArch64** [comment]
Options:
1. Scarlet trollstore IPA uses entitlements to generate anisette for free developer login for installs, it installs the apps as a user apps

2. Another option is if you install appsync unified then you can use Scarlet direct normally without any issues

3. If you have your own paid developer account or certificate you don't need any fancy method, just import into scarlet app and use for installs
