### ISSUE TITLE
Revoked 

### ISSUE THREAD

**Issue by ukcai696969** [DebianArch64/Scarlet#52]
When will the app be signed again?

**Comment by DebianArch64** [comment]
Not up to me, use anything other than scarlet direct and it'll work fine

Scarlet direct uses enterprise certificates, anything publicly available will be revoked pretty easily and since it's public it has to be leaked to the public before anything can be signed

**Comment by ukcai696969** [comment]
I would if i could, i only have a chromebook atm laptop broken so i can’t install with scarlet computer don’t think it’s possible on a chrome book
