### ISSUE TITLE
chromebook probably a stupid question 

### ISSUE THREAD

**Issue by ukcai696969** [DebianArch64/Scarlet#53]
is there away to download chromebook computer method from a chromebook to my phone?

**Comment by DebianArch64** [comment]
> is there away to download chromebook computer method from a chromebook to my phone?

This is a good question, see if the ScarletCloud Linux builds work on Chromebook you'll need usbmuxd installed

The computer method is getting a major rewrite so hopefully I'm able to test those things on the new build before release, but the new build should 100% be compatible
