### ISSUE TITLE
Multiple account signing

### ISSUE THREAD

**Issue by PsycloneTM** [DebianArch64/Scarlet#56]
If it's possible allow us to sign in with multiple free accounts to sign apps.

**Comment by DebianArch64** [comment]
> If it's possible allow us to sign in with multiple free accounts to sign apps.

Yes you can swap between accounts from the certificate menu:
But it's pointless in most circumstances:
- 3 app limit isn't per account it's per device
- 10 app id limit scarlet already has a bypass for

https://docs.usescarlet.com/scarlet/certificates-developer-login

**Comment by PsycloneTM** [comment]
> > If it's possible allow us to sign in with multiple free accounts to sign apps.
> 
> Yes you can swap between accounts from the certificate menu: But it's pointless in most circumstances:
> 
> * 3 app limit isn't per account it's per device
> * 10 app id limit scarlet already has a bypass for
> 
> https://docs.usescarlet.com/scarlet/certificates-developer-login

Oh I thought it was per account fuck that's dumb
