### ISSUE TITLE
that app cant be checked

### ISSUE THREAD

**Issue by elnarokeks** [DebianArch64/Scarlet#64]
after i deleted scarlet and downloaded it again i got an error
"Unable to check the application

To check the developer

"iPhone Distribution: Sunshine

Insurance Group Co., Ltd., is required

Network connection. This application will not be available until the end of the check"
![photo_2024-05-07_19-53-20](https://github.com/DebianArch64/Scarlet/assets/169185277/a290c994-f1aa-48fa-944b-31faa832269d)

**Comment by DebianArch64** [comment]
> after i deleted scarlet and downloaded it again i got an error "Unable to check the application
> 
> To check the developer
> 
> "iPhone Distribution: Sunshine
> 
> Insurance Group Co., Ltd., is required
> 
> Network connection. This application will not be available until the end of the check" ![photo_2024-05-07_19-53-20](https://private-user-images.githubusercontent.com/169185277/328610225-a290c994-f1aa-48fa-944b-31faa832269d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDEzNDAsIm5iZiI6MTcxNTEwMTA0MCwicGF0aCI6Ii8xNjkxODUyNzcvMzI4NjEwMjI1LWEyOTBjOTk0LWYxYWEtNDhmYS05NDRiLTMxZmFhODMyMjY5ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNjU3MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWFjMTMzYjY0Yjk2OGYxYTg3Y2NmZjg2MjMzNjg0OGY2ZjRmZmZkNWQ4N2Y3ZTdiYzhiMjJkNWI4MGMzM2VkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sS3Lhg5VPPA4CraQTwx4QhyeXMAF6QU-uDlwx7kfiA4)

This isn't related to Scarlet, apple has a trust cache that says information like what is revoked and what is "blacklisted"

The Internet connection message happens because iOS keeps statistics of what has been installed with an *enterprise* certificate and sees if it's been misused before with other users. Once it lists the certificate as misused on the device then it won't let the device check the status of the certificate

People nowadays just buy their own certificates and import that into Scarlet

**Comment by DebianArch64** [comment]
> and how get that thing off?

You don't (reset works but not worth it), treat it like a revoke but something that works on some devices and not others. Devices that haven't touched third party apps before are less likely to get them because apple loves tracking people

**Comment by elnarokeks** [comment]
so if i reset that thing will go off?

**Comment by DebianArch64** [comment]
> so if i reset that thing will go off?

If you reset the physical copy of what it says it doesn't like will be gone, but the one on the server will still exist

So the chances of being blacklisted again don't go away, but the "blacklist" does. I recommend buying a certificate from maplesign and importing that or using the scarlet computer method with wireguard for wireless installs
