### ISSUE TITLE
Does this work with IOS 18?

### ISSUE THREAD

**Issue by SkyKingPX** [DebianArch64/Scarlet#69]
I installed IOS 18 and then Scarlet. The phone wanted me to restart to approve the certificate and said that I can now use it and install third party apps.

I just need to know if I should keep the VPN with the blacklist on or not because of the fast revoked certificates.

**Comment by SkyKingPX** [comment]
It seems like I have not to. But after a month or so, I have to reinstall all apps.
But that is no problem anymore as it works every time

**Comment by DebianArch64** [comment]
Yeah iOS version doesn't matter, if you have your own certificate you can import into scarlet app

Scarlet direct uses public certificates that don't always work

**Comment by SkyKingPX** [comment]
I mean because iOS 18 allows installing 3rd-party Applications
