### ISSUE TITLE
Should I do something?

### ISSUE THREAD

**Issue by CukierDev** [DebianArch64/Scarlet#9]
When I installed scarlet the dot in the top right corner was green then it changed to orange and now it’s red what should I do?

I used direct install
![E6667227-693A-4EC6-832C-B4AD4C1502FF](https://user-images.githubusercontent.com/101931714/222713777-5838dfe2-2ced-45a7-90cc-93538de7bce8.jpeg)

**Comment by DebianArch64** [comment]
> When I installed scarlet the dot in the top right corner was green then it changed to orange and now it’s red what should I do?
> 
> I used direct install ![E6667227-693A-4EC6-832C-B4AD4C1502FF](https://user-images.githubusercontent.com/101931714/222713777-5838dfe2-2ced-45a7-90cc-93538de7bce8.jpeg)

Means a revoke is about to reach you - install Scarlet from the site to use the latest certificate

**Comment by CukierDev** [comment]
Thanks

**Comment by CukierDev** [comment]
But wait when I click on scarlet (or other sideloaded app) it says 282 days left to revoke

**Comment by CukierDev** [comment]
oh wait it says 348 days

**Comment by DebianArch64** [comment]
> oh wait it says 348 days

Expiration is the day it will always not work while revocation can happen anytime apple chooses

**Comment by CukierDev** [comment]
Tysm
